# Generated by Django 4.2.5 on 2023-09-19 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_carousel_description_poster_profile_startup_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(max_length=255),
        ),
    ]
